name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  lint-test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.11"]
        extras: ["", "crypto", "dcbor", "crypto,dcbor"]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install tools
        run: |
          python -m pip install --upgrade pip
          python -m pip install ruff pytest build
      - name: Install package (base)
        if: matrix.extras == ''
        run: |
          python -m pip install -e .
      - name: Install package (with extras)
        if: matrix.extras != ''
        run: |
          python -m pip install -e .[${{ matrix.extras }}]
      - name: Lint
        run: ruff check .
      - name: Build (sdist/wheel)
        run: python -m build
      - name: Test
        run: pytest -q
