name: Publish

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build-and-publish:
    name: build-and-publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install build tooling
        run: |
          python -m pip install --upgrade pip
          pip install build

      - name: Build package (sdist/wheel)
        run: python -m build

      - name: Upload dist artifacts
        uses: actions/upload-artifact@v4
        with:
          name: dist
          path: dist/*

      - name: Publish to TestPyPI (if token provided)
        env:
          TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        if: ${{ env.TOKEN }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ env.TOKEN }}
          repository-url: https://test.pypi.org/legacy/

      - name: Publish to PyPI (if token provided)
        env:
          TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        if: ${{ env.TOKEN }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          user: __token__
          password: ${{ env.TOKEN }}
